name: Build & Deploy

on:
  push:
    branches: [master]

jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Repository
        uses: actions/checkout@v2.0.0
      - name: Install Project Dependencies
        run: npm install
      - name: Build App
        run: npm run build
      - name: Build Documentation
        run: npm run docs:build
      - name: Deploy to Firebase Hosting
        uses: w9jds/firebase-action@v1.3.0
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
